import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { PrismaClient, UserRole, UserStatus } = require('../../server/node_modules/@prisma/client');

const apiBaseUrl = (process.env.API_BASE_URL || 'http://localhost:3000/api').replace(/\/$/, '');
const runId = Date.now();
const prisma = new PrismaClient();

async function main() {
  const owner = await registerUser('owner');
  const editor = await registerUser('editor');
  const viewer = await registerUser('viewer');

  const adminDenied = await request('/admin/overview', {
    token: editor.token,
    expectedStatus: 403,
  });
  assertEqual(adminDenied.code, 'FORBIDDEN', 'non-admin should not access admin overview');

  await grantAdminRole(owner.email);

  const me = await request('/auth/me', { token: owner.token });
  assertEqual(me.email, owner.email, 'auth/me should return registered owner');
  assertEqual(me.role, 'admin', 'granted owner should become platform admin');

  const adminOverview = await request('/admin/overview', { token: owner.token });
  if (adminOverview.users.total < 3) {
    throw new Error('admin overview should include registered smoke users');
  }

  const project = await request('/projects', {
    method: 'POST',
    token: owner.token,
    body: {
      name: `Smoke Project ${runId}`,
      description: 'Generated by scripts/smoke/api-smoke.mjs',
    },
  });
  assertEqual(project.currentUserRole, 'owner', 'project creator should be owner');

  const initialMembers = await request(`/projects/${project.id}/members`, { token: owner.token });
  assertEqual(initialMembers[0].role, 'owner', 'new project should contain owner member');

  const forbiddenBeforeInvite = await request(`/projects/${project.id}/pages`, {
    token: editor.token,
    expectedStatus: 403,
  });
  assertEqual(forbiddenBeforeInvite.code, 'PROJECT_FORBIDDEN', 'non-member should not read project pages');

  const editorMember = await request(`/projects/${project.id}/members`, {
    method: 'POST',
    token: owner.token,
    body: {
      email: editor.email,
      role: 'editor',
    },
  });
  assertEqual(editorMember.role, 'editor', 'owner should add editor member');

  const viewerMember = await request(`/projects/${project.id}/members`, {
    method: 'POST',
    token: owner.token,
    body: {
      email: viewer.email,
      role: 'viewer',
    },
  });
  assertEqual(viewerMember.role, 'viewer', 'owner should add viewer member');

  const editorProjects = await request('/projects', { token: editor.token });
  assertEqual(editorProjects[0].id, project.id, 'editor should see invited project');
  assertEqual(editorProjects[0].currentUserRole, 'editor', 'editor project list should include current role');

  const viewerCreateDenied = await request(`/projects/${project.id}/pages`, {
    method: 'POST',
    token: viewer.token,
    body: {
      name: 'Viewer Denied Page',
      routePath: `/viewer-denied-${runId}`,
    },
    expectedStatus: 403,
  });
  assertEqual(viewerCreateDenied.code, 'PROJECT_FORBIDDEN', 'viewer should not create pages');

  const page = await request(`/projects/${project.id}/pages`, {
    method: 'POST',
    token: editor.token,
    body: {
      name: 'Smoke Page',
      routePath: `/smoke-${runId}`,
    },
  });
  assertEqual(page.createdById, editor.user.id, 'editor should create page as actor');

  const viewerPages = await request(`/projects/${project.id}/pages`, { token: viewer.token });
  assertEqual(viewerPages[0].id, page.id, 'viewer should read pages');

  const viewerSaveDenied = await request(`/pages/${page.id}`, {
    method: 'PATCH',
    token: viewer.token,
    body: {
      name: 'Viewer Cannot Save',
    },
    expectedStatus: 403,
  });
  assertEqual(viewerSaveDenied.code, 'PROJECT_FORBIDDEN', 'viewer should not update pages');

  const savedPage = await request(`/pages/${page.id}`, {
    method: 'PATCH',
    token: editor.token,
    body: {
      schema: {
        schemaVersion: '1.0.0',
        pageId: page.id,
        components: [
          {
            id: 1,
            name: 'Page',
            props: {},
            desc: '页面',
            children: [
              {
                id: 2,
                name: 'Text',
                props: {
                  text: 'Smoke Test',
                },
                desc: '文本',
                parentId: 1,
              },
            ],
          },
        ],
        metadata: {
          smoke: true,
        },
      },
    },
  });

  assertEqual(savedPage.schema.components[0].children[0].name, 'Text', 'saved schema should keep Text component');

  const versions = await request(`/pages/${page.id}/versions`, { token: viewer.token });
  if (!Array.isArray(versions) || versions.length === 0) {
    throw new Error('saving page should create at least one version');
  }

  const publishedPage = await request(`/pages/${page.id}/publish`, {
    method: 'POST',
    token: editor.token,
  });

  if (!publishedPage.publicId) {
    throw new Error('publish should return publicId');
  }

  const publicPage = await request(`/public/pages/${publishedPage.publicId}`);
  assertEqual(publicPage.schema.components[0].children[0].props.text, 'Smoke Test', 'public page should read published snapshot');

  const publishedPages = await request('/admin/published-pages', { token: owner.token });
  assertIncludes(publishedPages.map((item) => item.id), page.id, 'admin should list published page');

  await request(`/admin/pages/${page.id}/unpublish`, {
    method: 'POST',
    token: owner.token,
  });

  const unpublishedPublicPage = await request(`/public/pages/${publishedPage.publicId}`, {
    expectedStatus: 404,
  });
  assertEqual(unpublishedPublicPage.code, 'PUBLISHED_PAGE_NOT_FOUND', 'admin unpublished page should no longer be public');

  const template = await request(`/projects/${project.id}/templates`, {
    method: 'POST',
    token: editor.token,
    body: {
      type: 'block',
      title: 'Smoke Template',
      description: 'Generated by smoke test',
      tags: ['smoke'],
      visibility: 'project',
      schema: {
        schemaVersion: '1.0.0',
        pageId: null,
        components: [
          {
            id: 1,
            name: 'Container',
            props: {},
            desc: 'Smoke Template Block',
            children: [
              {
                id: 2,
                name: 'Text',
                props: {
                  text: 'Template Text',
                },
                desc: '模板文本',
                parentId: 1,
              },
            ],
          },
        ],
        metadata: {
          smoke: true,
        },
      },
    },
  });
  assertEqual(template.title, 'Smoke Template', 'editor should create project template');

  const templates = await request(`/projects/${project.id}/templates`, { token: viewer.token });
  assertIncludes(templates.map((item) => item.id), template.id, 'viewer should read project templates');

  const viewerTemplateDenied = await request(`/projects/${project.id}/templates`, {
    method: 'POST',
    token: viewer.token,
    body: {
      type: 'block',
      title: 'Denied Template',
      schema: template.schema,
    },
    expectedStatus: 403,
  });
  assertEqual(viewerTemplateDenied.code, 'PROJECT_FORBIDDEN', 'viewer should not create templates');

  const asset = await uploadAsset(`/projects/${project.id}/assets`, {
    token: editor.token,
    filename: `smoke-${runId}.txt`,
    content: 'hello asset',
    type: 'text/plain',
  });
  assertEqual(asset.category, 'file', 'text upload should create file asset');

  const assets = await request(`/projects/${project.id}/assets`, { token: viewer.token });
  assertIncludes(assets.map((item) => item.id), asset.id, 'viewer should read project assets');

  const publicAssetResponse = await fetch(`${apiBaseUrl.replace(/\/api$/, '')}${asset.url}`);
  if (!publicAssetResponse.ok) {
    throw new Error(`public asset should be readable: ${publicAssetResponse.status}`);
  }
  assertEqual(await publicAssetResponse.text(), 'hello asset', 'public asset should return uploaded content');

  const viewerUploadDenied = await uploadAsset(`/projects/${project.id}/assets`, {
    token: viewer.token,
    filename: `denied-${runId}.txt`,
    content: 'denied',
    type: 'text/plain',
    expectedStatus: 403,
  });
  assertEqual(viewerUploadDenied.code, 'PROJECT_FORBIDDEN', 'viewer should not upload assets');

  await request(`/projects/${project.id}/members/${editorMember.id}`, {
    method: 'PATCH',
    token: owner.token,
    body: {
      role: 'viewer',
    },
  });

  const demotedEditorDenied = await request(`/pages/${page.id}/publish`, {
    method: 'POST',
    token: editor.token,
    expectedStatus: 403,
  });
  assertEqual(demotedEditorDenied.code, 'PROJECT_FORBIDDEN', 'demoted editor should lose write permission');

  await request(`/projects/${project.id}/members/${viewerMember.id}`, {
    method: 'DELETE',
    token: owner.token,
  });

  const auditLogs = await request(`/projects/${project.id}/audit-logs`, { token: owner.token });
  const actions = auditLogs.map((log) => log.action);
  assertIncludes(actions, 'project.member.add', 'audit logs should include member add');
  assertIncludes(actions, 'page.update', 'audit logs should include page save');
  assertIncludes(actions, 'page.publish', 'audit logs should include publish');
  assertIncludes(actions, 'template.create', 'audit logs should include template create');
  assertIncludes(actions, 'asset.upload', 'audit logs should include asset upload');

  const auditDenied = await request(`/projects/${project.id}/audit-logs`, {
    token: editor.token,
    expectedStatus: 403,
  });
  assertEqual(auditDenied.code, 'PROJECT_FORBIDDEN', 'non-owner should not read audit logs');

  const republishedPage = await request(`/pages/${page.id}/publish`, {
    method: 'POST',
    token: owner.token,
  });
  if (!republishedPage.publicId) {
    throw new Error('owner should be able to republish page before admin disable project');
  }

  await request(`/admin/projects/${project.id}/status`, {
    method: 'PATCH',
    token: owner.token,
    body: {
      status: 'disabled',
    },
  });

  const disabledProjectReadDenied = await request(`/projects/${project.id}/pages`, {
    token: editor.token,
    expectedStatus: 403,
  });
  assertEqual(disabledProjectReadDenied.code, 'PROJECT_FORBIDDEN', 'disabled project should reject member page reads');

  const disabledProjectPublicDenied = await request(`/public/pages/${republishedPage.publicId}`, {
    expectedStatus: 404,
  });
  assertEqual(disabledProjectPublicDenied.code, 'PUBLISHED_PAGE_NOT_FOUND', 'disabled project should hide public page');

  await request(`/admin/users/${viewer.user.id}/status`, {
    method: 'PATCH',
    token: owner.token,
    body: {
      status: 'disabled',
    },
  });

  const disabledViewerDenied = await request('/auth/me', {
    token: viewer.token,
    expectedStatus: 401,
  });
  assertEqual(disabledViewerDenied.code, 'AUTH_ACCOUNT_DISABLED', 'disabled user token should stop working');

  const globalAuditLogs = await request('/admin/audit-logs', { token: owner.token });
  const globalActions = globalAuditLogs.map((log) => log.action);
  assertIncludes(globalActions, 'admin.page.unpublish', 'global audit should include admin unpublish');
  assertIncludes(globalActions, 'admin.project.disable', 'global audit should include project disable');
  assertIncludes(globalActions, 'admin.user.disable', 'global audit should include user disable');

  console.log(JSON.stringify({
    ok: true,
    apiBaseUrl,
    ownerId: owner.user.id,
    editorId: editor.user.id,
    viewerId: viewer.user.id,
    projectId: project.id,
    pageId: page.id,
    templateId: template.id,
    assetId: asset.id,
    publicId: publishedPage.publicId,
    adminAuditLogCount: globalAuditLogs.length,
    auditLogCount: auditLogs.length,
  }, null, 2));
}

async function grantAdminRole(email) {
  await prisma.user.update({
    where: { email },
    data: {
      role: UserRole.ADMIN,
      status: UserStatus.ACTIVE,
    },
  });
}

async function registerUser(prefix) {
  const email = `smoke-${prefix}-${runId}@example.com`;
  const username = `smoke_${prefix}_${runId}`;
  const password = 'password123';
  const response = await request('/auth/register', {
    method: 'POST',
    body: {
      email,
      username,
      password,
    },
  });

  if (!response.accessToken) {
    throw new Error(`${prefix} register did not return accessToken`);
  }

  return {
    email,
    username,
    password,
    token: response.accessToken,
    user: response.user,
  };
}

async function request(path, options = {}) {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    method: options.method || 'GET',
    headers: {
      ...(options.body ? { 'content-type': 'application/json' } : {}),
      ...(options.token ? { authorization: `Bearer ${options.token}` } : {}),
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
  });

  const text = await response.text();
  const data = text ? JSON.parse(text) : null;

  if (options.expectedStatus !== undefined) {
    if (response.status !== options.expectedStatus) {
      throw new Error(`${options.method || 'GET'} ${path} failed: expected ${options.expectedStatus}, received ${response.status} ${JSON.stringify(data)}`);
    }

    return data;
  }

  if (!response.ok) {
    throw new Error(`${options.method || 'GET'} ${path} failed: ${response.status} ${JSON.stringify(data)}`);
  }

  return data;
}

async function uploadAsset(path, options) {
  const formData = new FormData();
  formData.append('file', new Blob([options.content], { type: options.type }), options.filename);

  const response = await fetch(`${apiBaseUrl}${path}`, {
    method: 'POST',
    headers: {
      ...(options.token ? { authorization: `Bearer ${options.token}` } : {}),
    },
    body: formData,
  });

  const text = await response.text();
  const data = text ? JSON.parse(text) : null;

  if (options.expectedStatus !== undefined) {
    if (response.status !== options.expectedStatus) {
      throw new Error(`POST ${path} upload failed: expected ${options.expectedStatus}, received ${response.status} ${JSON.stringify(data)}`);
    }

    return data;
  }

  if (!response.ok) {
    throw new Error(`POST ${path} upload failed: ${response.status} ${JSON.stringify(data)}`);
  }

  return data;
}

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    throw new Error(`${message}: expected ${JSON.stringify(expected)}, received ${JSON.stringify(actual)}`);
  }
}

function assertIncludes(values, expected, message) {
  if (!values.includes(expected)) {
    throw new Error(`${message}: expected ${JSON.stringify(values)} to include ${expected}`);
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
