export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFIG_INVALID = 'CONFIG_INVALID',

  AUTH_ACCOUNT_EXISTS = 'AUTH_ACCOUNT_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',

  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_FORBIDDEN = 'PROJECT_FORBIDDEN',
  PROJECT_MEMBER_NOT_FOUND = 'PROJECT_MEMBER_NOT_FOUND',
  PROJECT_MEMBER_CONFLICT = 'PROJECT_MEMBER_CONFLICT',
  PROJECT_OWNER_IMMUTABLE = 'PROJECT_OWNER_IMMUTABLE',

  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
  PAGE_ROUTE_CONFLICT = 'PAGE_ROUTE_CONFLICT',
  PAGE_SCHEMA_INVALID = 'PAGE_SCHEMA_INVALID',
  PAGE_VERSION_NOT_FOUND = 'PAGE_VERSION_NOT_FOUND',
  PUBLISHED_PAGE_NOT_FOUND = 'PUBLISHED_PAGE_NOT_FOUND',
}
