import type { ComponentConfig } from '../types';
import TableColumnDev from '../../materials/TableColumn/dev';
import TableColumnProd from '../../materials/TableColumn/prod';
import TableDev from '../../materials/Table/dev';
import TableProd from '../../materials/Table/prod';
import {
  ChartDev,
  ChartProd,
  DescriptionsDev,
  DescriptionsProd,
  ListDev,
  ListProd,
  PaginationDev,
  PaginationProd,
  StatisticDev,
  StatisticProd,
} from '../../materials/p3';
import {
  clickEvents,
  commonStyleSetters,
  defineEvent,
  inputSetter,
  jsonSetter,
  numberSetter,
  selectSetter,
  switchSetter,
  urlSetter,
} from '../factory';

export const dataComponentConfigs: Record<string, ComponentConfig> = {
Table: {
            name: 'Table',
            defaultProps: {
                dataSourceId: '',
                dataText: '[{"id":1,"name":"张三","status":"启用","createdAt":"2026-05-08"},{"id":2,"name":"李四","status":"停用","createdAt":"2026-05-07"}]',
                pagination: false,
                pageSize: 10,
                emptyText: '暂无数据',
                rowKey: 'id',
            },
            desc: '表格',
            acceptsChildren: ['TableColumn'],
            category: 'data',
            icon: '▦',
            keywords: ['table', 'data', '表格', '数据'],
            sort: 10,
            setter: [
                inputSetter('dataSourceId', '数据源 ID', { group: 'data', placeholder: '如 table' }),
                urlSetter('url', '数据接口', { group: 'data' }),
                jsonSetter('dataText', '静态数据', {
                    group: 'data',
                    rows: 5,
                    placeholder: '[\n  { "id": 1, "name": "张三" }\n]',
                }),
                switchSetter('pagination', '开启分页', { help: '开启后表格按页展示数据。' }),
                numberSetter('pageSize', '每页条数', { min: 1, max: 100, help: '分页开启时每页展示的数据数量。' }),
                inputSetter('emptyText', '空状态文案'),
                inputSetter('rowKey', '行主键字段', { help: '用于稳定识别每一行数据，建议使用唯一 id 字段。' }),
                switchSetter('bordered', '显示边框', { help: '开启后表格展示外框和单元格边框。' }),
                switchSetter('showHeader', '显示表头', { help: '控制表格列标题行是否显示。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '表格变化事件', 'value', '分页、筛选或排序变化时触发', ['value', 'args']),
            ],
            dev: TableDev,
            prod: TableProd
        },
TableColumn: {
            name: 'TableColumn',
            desc: '表格列',
            category: 'data',
            icon: '▥',
            keywords: ['table column', 'column', '表格列', '列'],
            sort: 20,
            defaultProps: {
                dataIndex: 'name',
                title: '列名',
                type: 'text',
                actionText: '查看',
                actionUrl: '',
            },
            setter: [
                selectSetter('type', '类型', [
                    { label: '文本', value: 'text' },
                    { label: '日期', value: 'date' },
                    { label: '操作', value: 'action' },
                ]),
                inputSetter('title', '标题'),
                inputSetter('dataIndex', '字段'),
                numberSetter('width', '宽度'),
                inputSetter('format', '日期格式'),
                inputSetter('actionText', '操作文案'),
                urlSetter('actionUrl', '操作链接'),
                selectSetter('target', '打开方式', [
                    { label: '当前窗口', value: '_self' },
                    { label: '新窗口', value: '_blank' },
                ]),
            ],
            dev: TableColumnDev,
            prod: TableColumnProd,
        },
List: {
            name: 'List',
            defaultProps: {
                bordered: true,
                dataText: '[{"id":1,"title":"列表项一","description":"说明内容"},{"id":2,"title":"列表项二","description":"说明内容"}]',
            },
            desc: '列表',
            category: 'data',
            icon: '☰',
            keywords: ['list', '列表'],
            sort: 30,
            setter: [
                jsonSetter('dataText', '列表数据', {
                    group: 'data',
                    rows: 5,
                    placeholder: '[\n  { "title": "列表项", "description": "说明" }\n]',
                }),
                switchSetter('bordered', '显示边框', { help: '开启后列表展示外边框。' }),
                selectSetter('itemLayout', '列表布局', [
                    { label: '水平', value: 'horizontal' },
                    { label: '垂直', value: 'vertical' },
                ], { group: 'advanced' }),
            ],
            stylesSetter: commonStyleSetters,
            events: clickEvents,
            dev: ListDev,
            prod: ListProd,
        },
Descriptions: {
            name: 'Descriptions',
            defaultProps: {
                title: '详情信息',
                pairsText: '姓名:张三\n角色:管理员\n状态:启用',
                column: 2,
                bordered: true,
            },
            desc: '描述列表',
            category: 'data',
            icon: '≡',
            keywords: ['descriptions', '详情', '描述列表'],
            sort: 40,
            setter: [
                inputSetter('title', '标题'),
                inputSetter('pairsText', '字段配置'),
                numberSetter('column', '列数'),
                switchSetter('bordered', '显示边框', { help: '开启后描述列表展示表格式边框。' }),
                selectSetter('size', '尺寸', [
                    { label: '默认', value: 'default' },
                    { label: '中等', value: 'middle' },
                    { label: '紧凑', value: 'small' },
                ]),
            ],
            stylesSetter: commonStyleSetters,
            events: clickEvents,
            dev: DescriptionsDev,
            prod: DescriptionsProd,
        },
Statistic: {
            name: 'Statistic',
            defaultProps: {
                title: '指标标题',
                value: 128,
                suffix: '',
                prefix: '',
            },
            desc: '统计数值',
            category: 'data',
            icon: '№',
            keywords: ['statistic', '指标', '统计'],
            sort: 50,
            setter: [
                inputSetter('title', '标题'),
                inputSetter('value', '数值'),
                inputSetter('prefix', '前缀'),
                inputSetter('suffix', '后缀'),
                numberSetter('precision', '小数位数', { min: 0, max: 6 }),
            ],
            stylesSetter: commonStyleSetters,
            events: clickEvents,
            dev: StatisticDev,
            prod: StatisticProd,
        },
Pagination: {
            name: 'Pagination',
            defaultProps: {
                current: 1,
                total: 50,
                pageSize: 10,
            },
            desc: '分页',
            category: 'data',
            icon: '…',
            keywords: ['pagination', '分页'],
            sort: 60,
            setter: [
                numberSetter('current', '当前页'),
                numberSetter('total', '总数'),
                numberSetter('pageSize', '每页条数'),
                switchSetter('showSizeChanger', '允许切换条数', { help: '允许用户在分页器中切换每页条数。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '分页变化事件', 'value', '页码或每页条数变化时触发', ['page', 'pageSize', 'args']),
            ],
            dev: PaginationDev,
            prod: PaginationProd,
        },
Chart: {
            name: 'Chart',
            defaultProps: {
                title: '趋势图',
                dataText: '一月:30\n二月:52\n三月:76\n四月:48',
            },
            desc: '图表',
            category: 'data',
            icon: '▰',
            keywords: ['chart', '图表', '柱状图'],
            sort: 70,
            setter: [
                inputSetter('title', '标题'),
                inputSetter('dataText', '数据', {
                    group: 'data',
                    help: '每行一条，格式：名称:数值',
                }),
            ],
            stylesSetter: commonStyleSetters,
            events: clickEvents,
            dev: ChartDev,
            prod: ChartProd,
        },
};
