import type { ComponentConfig } from '../types';
import FormDev from '../../materials/Form/dev';
import FormItemDev from '../../materials/FormItem/dev';
import FormItemProd from '../../materials/FormItem/prod';
import FormProd from '../../materials/Form/prod';
import InputDev from '../../materials/Input/dev';
import InputProd from '../../materials/Input/prod';
import SelectDev from '../../materials/Select/dev';
import SelectProd from '../../materials/Select/prod';
import SwitchDev from '../../materials/Switch/dev';
import SwitchProd from '../../materials/Switch/prod';
import {
  CheckboxDev,
  CheckboxProd,
  DatePickerDev,
  DatePickerProd,
  RadioDev,
  RadioProd,
  RateDev,
  RateProd,
  TextareaDev,
  TextareaProd,
  UploadDev,
  UploadProd,
} from '../../materials/p3';
import {
  commonStyleSetters,
  defineEvent,
  inputSetter,
  numberSetter,
  selectSetter,
  switchSetter,
  valueChangeEvent,
} from '../factory';

export const formComponentConfigs: Record<string, ComponentConfig> = {
Input: {
            name: 'Input',
            defaultProps: {
                placeholder: '请输入',
                defaultValue: '',
                disabled: false,
                allowClear: true,
            },
            desc: '输入框',
            category: 'form',
            icon: 'I',
            keywords: ['input', 'field', '输入框'],
            sort: 10,
            setter: [
                inputSetter('placeholder', '占位提示', { placeholder: '请输入' }),
                inputSetter('defaultValue', '默认值'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法输入或修改内容。' }),
                switchSetter('allowClear', '允许清除', { help: '输入框右侧显示一键清空按钮。' }),
                numberSetter('maxLength', '最大长度', { group: 'advanced', min: 1 }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '值变化事件', 'value', '输入框内容变化时触发', ['value', 'args']),
                defineEvent('pressEnter', '回车事件', 'value', '输入框按下回车时触发', ['value', 'args'], ['toast', 'url', 'componentAction', 'custom']),
                defineEvent('blur', '失焦事件', 'value', '输入框失去焦点时触发', ['value', 'args']),
            ],
            dev: InputDev,
            prod: InputProd,
        },
Textarea: {
            name: 'Textarea',
            defaultProps: {
                placeholder: '请输入多行文本',
                defaultValue: '',
                rows: 3,
                disabled: false,
            },
            desc: '多行输入',
            category: 'form',
            icon: '¶',
            keywords: ['textarea', '多行', '输入框'],
            sort: 20,
            setter: [
                inputSetter('placeholder', '占位提示'),
                inputSetter('defaultValue', '默认值'),
                numberSetter('rows', '行数'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法输入或修改内容。' }),
                switchSetter('showCount', '显示字数', { help: '在输入框下方显示当前字数和最大字数。' }),
                numberSetter('maxLength', '最大长度', { group: 'advanced', min: 1 }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '值变化事件', 'value', '内容变化时触发', ['value', 'args']),
                defineEvent('blur', '失焦事件', 'value', '输入框失去焦点时触发', ['value', 'args']),
            ],
            dev: TextareaDev,
            prod: TextareaProd,
        },
Select: {
            name: 'Select',
            defaultProps: {
                placeholder: '请选择',
                optionsText: '选项一,选项二,选项三',
                disabled: false,
            },
            desc: '下拉框',
            category: 'form',
            icon: '⌄',
            keywords: ['select', 'dropdown', '下拉框'],
            sort: 30,
            setter: [
                inputSetter('placeholder', '占位提示'),
                inputSetter('optionsText', '选项', {
                    group: 'data',
                    help: '用逗号或换行分隔选项。',
                }),
                inputSetter('defaultValue', '默认值'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法选择选项。' }),
                switchSetter('allowClear', '允许清除', { help: '允许用户清空当前选择。' }),
                selectSetter('mode', '选择模式', [
                    { label: '单选', value: '' },
                    { label: '多选', value: 'multiple' },
                    { label: '标签', value: 'tags' },
                ], { group: 'advanced' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '值变化事件', 'value', '下拉框选中值变化时触发', ['value', 'option', 'args']),
            ],
            dev: SelectDev,
            prod: SelectProd,
        },
Radio: {
            name: 'Radio',
            defaultProps: {
                optionsText: '选项一,选项二,选项三',
                defaultValue: '选项一',
                disabled: false,
            },
            desc: '单选框',
            category: 'form',
            icon: '○',
            keywords: ['radio', '单选'],
            sort: 40,
            setter: [
                inputSetter('optionsText', '选项', { group: 'data' }),
                inputSetter('defaultValue', '默认值'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法选择。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [valueChangeEvent],
            dev: RadioDev,
            prod: RadioProd,
        },
Checkbox: {
            name: 'Checkbox',
            defaultProps: {
                optionsText: '选项一,选项二,选项三',
                defaultValue: '选项一',
                disabled: false,
            },
            desc: '多选框',
            category: 'form',
            icon: '☑',
            keywords: ['checkbox', '多选'],
            sort: 50,
            setter: [
                inputSetter('optionsText', '选项', { group: 'data' }),
                inputSetter('defaultValue', '默认值'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法选择。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [valueChangeEvent],
            dev: CheckboxDev,
            prod: CheckboxProd,
        },
DatePicker: {
            name: 'DatePicker',
            defaultProps: {
                placeholder: '请选择日期',
                defaultValue: '',
                disabled: false,
            },
            desc: '日期选择',
            category: 'form',
            icon: '日',
            keywords: ['date', 'datepicker', '日期'],
            sort: 60,
            setter: [
                inputSetter('placeholder', '占位提示'),
                inputSetter('defaultValue', '默认值'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法选择日期。' }),
                inputSetter('format', '日期格式', { group: 'advanced', placeholder: 'YYYY-MM-DD' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '值变化事件', 'value', '日期变化时触发', ['value', 'dateString', 'args']),
            ],
            dev: DatePickerDev,
            prod: DatePickerProd,
        },
Switch: {
            name: 'Switch',
            defaultProps: {
                checked: false,
                disabled: false,
                checkedChildren: '开',
                unCheckedChildren: '关',
            },
            desc: '开关',
            category: 'form',
            icon: '◉',
            keywords: ['switch', 'toggle', '开关'],
            sort: 70,
            setter: [
                switchSetter('checked', '默认开启', { help: '设置开关初始状态为开启。' }),
                inputSetter('checkedChildren', '开启文案'),
                inputSetter('unCheckedChildren', '关闭文案'),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法切换开关。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '值变化事件', 'value', '开关状态变化时触发', ['checked', 'value', 'args']),
            ],
            dev: SwitchDev,
            prod: SwitchProd,
        },
Upload: {
            name: 'Upload',
            defaultProps: {
                buttonText: '上传文件',
                disabled: false,
            },
            desc: '上传',
            category: 'form',
            icon: '⇧',
            keywords: ['upload', '上传', '文件'],
            sort: 80,
            setter: [
                inputSetter('buttonText', '按钮文案'),
                inputSetter('accept', '允许类型', { group: 'advanced', placeholder: '.png,.jpg' }),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法上传文件。' }),
                switchSetter('multiple', '允许多选', { help: '允许一次选择多个文件。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('change', '文件变化事件', 'value', '上传文件列表变化时触发', ['value', 'args']),
            ],
            dev: UploadDev,
            prod: UploadProd,
        },
Rate: {
            name: 'Rate',
            defaultProps: {
                defaultValue: 3,
                count: 5,
                disabled: false,
            },
            desc: '评分',
            category: 'form',
            icon: '★',
            keywords: ['rate', '评分'],
            sort: 90,
            setter: [
                numberSetter('defaultValue', '默认值'),
                numberSetter('count', '数量'),
                switchSetter('allowHalf', '允许半星', { help: '允许评分选择 0.5 的半星值。' }),
                switchSetter('disabled', '禁用', { help: '禁用后用户无法修改评分。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [valueChangeEvent],
            dev: RateDev,
            prod: RateProd,
        },
Form: {
            name: 'Form',
            defaultProps: {
                title: '表单',
                layout: 'horizontal',
                showActions: true,
                submitText: '提交',
                resetText: '重置',
            },
            desc: '表单',
            acceptsChildren: ['FormItem'],
            category: 'form',
            icon: '▧',
            keywords: ['form', 'submit', '表单', '提交'],
            sort: 100,
            setter: [
                inputSetter('title', '标题'),
                selectSetter('layout', '表单布局', [
                    { label: '水平', value: 'horizontal' },
                    { label: '垂直', value: 'vertical' },
                    { label: '行内', value: 'inline' },
                ]),
                switchSetter('showActions', '显示按钮', { help: '控制表单底部提交和重置按钮是否显示。' }),
                inputSetter('submitText', '提交文案'),
                inputSetter('resetText', '重置文案'),
                switchSetter('disabled', '整体禁用', { group: 'advanced', help: '禁用整个表单内的输入控件。' }),
            ],
            stylesSetter: commonStyleSetters,
            events: [
                defineEvent('finish', '提交成功', 'submit', '表单校验通过并提交成功时触发', ['values', 'args']),
                defineEvent('finishFailed', '提交失败', 'submit', '表单校验失败时触发', ['values', 'errorFields', 'outOfDate', 'args'], ['toast', 'condition', 'custom']),
                defineEvent('valuesChange', '值变化事件', 'value', '任意表单字段变化时触发', ['changedValues', 'allValues', 'args']),
            ],
            methods: [
                { name: 'submit', label: '提交' },
                { name: 'reset', label: '重置' },
                { name: 'getValues', label: '读取表单数据' },
                { name: 'setValues', label: '设置表单数据' },
            ],
            dev: FormDev,
            prod: FormProd
        },
FormItem: {
            name: 'FormItem',
            desc: '表单项',
            category: 'form',
            icon: '▨',
            keywords: ['form item', 'field', '表单项', '字段'],
            sort: 110,
            defaultProps: {
                name: 'field',
                label: '字段',
                type: 'input',
                placeholder: '请输入',
                defaultValue: '',
                optionsText: '选项一,选项二',
            },
            dev: FormItemDev,
            prod: FormItemProd,
            setter: [
                selectSetter('type', '类型', [
                    { label: '文本', value: 'input' },
                    { label: '多行文本', value: 'textarea' },
                    { label: '日期', value: 'date' },
                    { label: '下拉', value: 'select' },
                    { label: '单选', value: 'radio' },
                    { label: '多选', value: 'checkbox' },
                    { label: '开关', value: 'switch' },
                    { label: '评分', value: 'rate' },
                ]),
                inputSetter('label', '标题'),
                inputSetter('name', '字段'),
                inputSetter('placeholder', '占位提示'),
                inputSetter('defaultValue', '默认值'),
                inputSetter('optionsText', '选项', { group: 'data' }),
                selectSetter('rules', '校验', [
                    { label: '无', value: '' },
                    { label: '必填', value: 'required' },
                    { label: '邮箱', value: 'email' },
                ]),
                switchSetter('required', '必填标记', { group: 'advanced' }),
            ]
        },
};
