import type { LowcodeComponentConfigMap } from './types';

const commonChildren = [
  'Text',
  'Image',
  'Divider',
  'Card',
  'Alert',
  'Input',
  'Textarea',
  'Select',
  'Radio',
  'Checkbox',
  'DatePicker',
  'Switch',
  'Rate',
  'Upload',
  'Button',
  'Link',
  'Icon',
  'Space',
  'Flex',
  'Grid',
  'Tabs',
  'Steps',
  'List',
  'Descriptions',
  'Statistic',
  'Pagination',
  'Chart',
  'Tooltip',
  'Popover',
  'Notification',
  'Result',
  'Empty',
  'Container',
  'Table',
  'Form',
  'Drawer',
];

const pageChildren = [...commonChildren, 'Modal'];

export const builtinComponentSchemaRegistry: LowcodeComponentConfigMap = {
  Page: {
    name: 'Page',
    acceptsChildren: pageChildren,
  },
  Container: {
    name: 'Container',
    acceptsChildren: pageChildren,
  },
  Card: {
    name: 'Card',
    acceptsChildren: pageChildren,
  },
  Space: {
    name: 'Space',
    acceptsChildren: commonChildren,
  },
  Flex: {
    name: 'Flex',
    acceptsChildren: commonChildren,
  },
  Grid: {
    name: 'Grid',
    acceptsChildren: commonChildren,
  },
  Modal: {
    name: 'Modal',
    acceptsChildren: commonChildren,
  },
  Drawer: {
    name: 'Drawer',
    acceptsChildren: commonChildren,
  },
  Table: {
    name: 'Table',
    acceptsChildren: ['TableColumn'],
  },
  Form: {
    name: 'Form',
    acceptsChildren: ['FormItem'],
  },
  Button: { name: 'Button' },
  Link: { name: 'Link' },
  Icon: { name: 'Icon' },
  Text: { name: 'Text' },
  Image: { name: 'Image' },
  Divider: { name: 'Divider' },
  Alert: { name: 'Alert' },
  Input: { name: 'Input' },
  Textarea: { name: 'Textarea' },
  Select: { name: 'Select' },
  Radio: { name: 'Radio' },
  Checkbox: { name: 'Checkbox' },
  DatePicker: { name: 'DatePicker' },
  Switch: { name: 'Switch' },
  Upload: { name: 'Upload' },
  Rate: { name: 'Rate' },
  Tabs: { name: 'Tabs' },
  Steps: { name: 'Steps' },
  List: { name: 'List' },
  Descriptions: { name: 'Descriptions' },
  Statistic: { name: 'Statistic' },
  Pagination: { name: 'Pagination' },
  Chart: { name: 'Chart' },
  Tooltip: { name: 'Tooltip' },
  Popover: { name: 'Popover' },
  Notification: { name: 'Notification' },
  Result: { name: 'Result' },
  Empty: { name: 'Empty' },
  TableColumn: { name: 'TableColumn' },
  FormItem: { name: 'FormItem' },
};
